# fly.toml app configuration file generated for akilic-reactivities on 2023-10-27T11:54:02+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "akilic-reactivities"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []


[build]
  image = "alperenkilic97/reactivities-revamped:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dsukjmz7q"
  Cloudinary__ApiKey="134513526792311"
  Facebook__AppId="1047529889773805"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
